site_name: pyHLAMSA
repo_url: https://github.com/linnil1/pyHLAMSA
theme:
  name: material
  features:
    - toc.integrate

extra_css:
- css/mkdocstrings.css

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        selection:
          docstring_style: google
          inherited_members: True
        rendering:
          show_source: True
          merge_init_into_class: True
          show_signature_annotations: True
          separate_signature: True
          show_if_no_docstring: True
    watch:
      - pyhlamsa
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
