name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install temporary packages for document and testing
        run: pip install mkdocs-material mkdocstrings==0.18.0 mkdocstrings-python-legacy pytest black mypy
      - name: Install this package
        run: pip install .
      - name: Test
        run: pytest
      - name: Test code style
        run: black --check pyhlamsa
      - name: Test type
        run: mypy pyhlamsa
      - name: Deploy web
        run: mkdocs gh-deploy --force
