name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install temporary packages for document and testing mypy
        run: pip install mkdocs-material mkdocstrings pytest pycodestyle
      - name: Install this package
        run: pip install .
      - name: Test
        run: pytest
      - name: Test code style
        run: pycodestyle pyHLAMSA/*.py
      - name: Test type
        run: mypy pyHLAMSA/*.py
      - name: Deploy web
        run: mkdocs gh-deploy --force
